<?php
/**
 * Created by PhpStorm.
 * User: Vaara
 * Date: 31.03.2019
 * Time: 16:06
 */
namespace app\models\prizes;

use app\interfaces\PrizeInterface;
use app\models\ActiveRecord\Wins;

class Money extends Prize {


    public static function create($value) {
        $money = \app\models\ActiveRecord\Money::create($value);
        MoneyPool::subtractAvailable($value);
        return static::get(Wins::create($money));
    }

    public function decline()
    {
        MoneyPool::addAvailable($this->_object->moneyData->value);
        return parent::decline(); // TODO: Change the autogenerated stub
    }


}